config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  resources :main, only: [:index] do
    collection do
      post 'send', to: "main#done"
    end
  end
  
  get  'test', to: 'messages#test'
  post 'confirm', to: 'messages#confirm'
  post 'done', to: 'messages#done'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @message = Message.new
  end

  def done
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.received_email(@message).deliver_now
      redirect_to root_path, notice: "メッセージありがとうございました"
    else
      flash.now[:alert] = "メッセージが送信できませんでした"
      render action: 'index'
    end
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def test
    @message = Message.new
  end
 
  def confirm
    @message = Message.new(message_params)
    if @message.valid?
      render action: 'confirm'
    else
      render action: 'test'
    end
  end
 
  def done
    @message = Message.new(message_params)
    if params[:back]
      render action: 'test'
    else
      MessageMailer.received_email(@message).deliver_now
      render action: 'done'
    end
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "”width=device-width, initial-scale=1.0″", :name => "”viewport”"}/
    %title My Portfolio | 岩崎 しょうこ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}/
  %body
    = yield

app/views/main/_contact.html.haml
.contact__form
  = form_for(message,url: {controller: "main", action: "done"}) do |f|
    .contact__form__input
      %p= f.text_field :name, placeholder: 'Name'
      %i.fa.fa-user.fa-lg.fa-fw
    .contact__form__input
      %p= f.text_field :email, placeholder: 'E-Mail'
      %i.fa.fa-envelope.fa-lg.fa-fw
    .contact__form__textarea
      %p= f.text_area :content, placeholder: 'Comment'
    .contact__form__btn
      = f.hidden_field :rendering, class: "st", value: ""
      = f.submit 'Send', class: "btn"
    .contact__form__error
      = render "flash"

app/views/main/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "notifications")

app/views/messages/confirm.html.haml
= form_for @message, url: done_path do |f|
  %div
    %h2 メッセージ確認
    %div
      %strong 名前
      %p
        = f.hidden_field :name
        = @message.name
    %div
      %strong メールアドレス
      %p
        = f.hidden_field :email
        = @message.email
    %div
      %strong 内容
      %p
        = f.hidden_field :content
        = simple_format(@message.content)
    = f.submit '戻る', name: 'back'
    = f.submit '送信する'

app/views/messages/done.html.haml
%div
  %h2 メッセージ送信完了
  %p
    メッセージをいただきありがとうございました。

app/views/messages/index.html.haml
= form_for(@message, url: { action: :confirm }) do |f|
  %div
    %h2 Contact
    - if @message.errors.present?
      %div
        %strong 入力内容にエラーがあります
        %ul
          - @message.errors.each do |attr, error|
            %li= error
    %div
      %strong Name
      %p= f.text_field :name, placeholder: 'Name'
    %div
      %strong Mail
      %p= f.text_field :email, placeholder: 'Mail'
    %div
      %strong comment
      %p= f.text_area :content
    = f.submit '確認画面へ'

app/views/messages/test.html.haml
= form_for(@message, url: { action: :confirm }) do |f|
  %div
    %h2 Contact
    - if @message.errors.present?
      %div
        %strong 入力内容にエラーがあります
        %ul
          - @message.errors.each do |attr, error|
            %li= error
    %div
      %strong Name
      %p= f.text_field :name, placeholder: 'Name'
    %div
      %strong Mail
      %p= f.text_field :email, placeholder: 'Mail'
    %div
      %strong comment
      %p= f.text_area :content
    = f.submit '確認画面へ'